export const CONFIG_COLUNAS = [


  {chave: 'edicao', label: 'Edição', tipo: 'text', categoria: 'Básico'},
  { chave: 'data_pdf', label: 'Data PDF', tipo: 'date', categoria: 'Básico' },
  { chave: 'prazo_entrega', label: 'Prazo de Entrega', tipo: 'date', categoria: 'Básico' },
  { chave: 'descricao', label: 'Descrição', tipo: 'textarea', categoria: 'Básico' },
  { chave: 'chamada_principal', label: 'Chamada Principal', tipo: 'textarea', categoria: 'Básico' },
  { chave: 'descricao_edicao', label: 'Descrição Edição', tipo: 'textarea', categoria: 'Básico' },
  { chave: 'palavra_chave', label: 'Palavra Chave', tipo: 'text', categoria: 'Básico' },
  { chave: 'autor', label: 'Autor', tipo: 'text', categoria: 'Básico' },
  { chave: 'numero_paginas', label: 'Número de Páginas', tipo: 'number', categoria: 'Básico' },
  { chave: 'codigo_barra', label: 'Código de Barra', tipo: 'text', categoria: 'Básico' },
  { chave: 'ean', label: 'EAN', tipo: 'text', categoria: 'Básico' },
  { chave: 'isbn', label: 'ISBN', tipo: 'text', categoria: 'Básico' },
  { chave: 'bisac', label: 'BISAC', tipo: 'text', categoria: 'Básico' },
  { chave: 'descricao_bisac', label: 'Descrição BISAC', tipo: 'textarea', categoria: 'Básico' },
  { chave: 'cate', label: 'Categoria', tipo: 'text', categoria: 'Básico' },
 { chave: 'sub_categoria', label: 'Sub Categoria', tipo: 'text', categoria: 'Básico' },
 { chave: 'editora', label: 'Editora', tipo: 'text', categoria: 'Básico' },
 { chave: 'periodicidade', label: 'Periodicidade', tipo: 'text', categoria: 'Básico' },
 { chave: 'observacoes', label: 'Observações', tipo: 'textarea', categoria: 'Básico' },
  
  { chave: 'google_negocios_digital', label: 'Google Negócios Digital', tipo: 'text', categoria: 'Google Negócios' },
  { chave: 'google_negocios_impresso', label: 'Google Negócios Impresso', tipo: 'text', categoria: 'Google Negócios' },
  { chave: 'via_varejo_impresso', label: 'Via Varejo Impresso', tipo: 'text', categoria: 'Via Varejo' },
  { chave: 'digitaliza_pdf', label: 'Digitaliza PDF', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_epub', label: 'Digitaliza EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_metadados_digit', label: 'Digitaliza Metadados Digit', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_solic_exclusao', label: 'Digitaliza Solic Exclusão', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_24symbolo_epub', label: 'Digitaliza 24Symbolo EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_amazom_epub', label: 'Digitaliza Amazom EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_apple_epub', label: 'Digitaliza Apple EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_arvoresdelivros_epub', label: 'Digitaliza Árvores de Livros EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_bem_te_li_epub', label: 'Digitaliza Bem-te-li EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_google_pdf', label: 'Digitaliza Google PDF', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_kobo_epub', label: 'Digitaliza Kobo EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_livraria_cultura_epub', label: 'Digitaliza Livraria Cultura EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_nook_barners_noble', label: 'Digitaliza Nook Barnes Noble', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_saraiva', label: 'Digitaliza Saraiva', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_toca_livros', label: 'Digitaliza Toca Livros', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_ubook', label: 'Digitaliza Ubook', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_ubool_store_epub', label: 'Digitaliza Ubool Store EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_', label: 'Digitaliza', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_epub_enviado', label: 'Digitaliza EPUB Enviado', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_aprovado_enviado', label: 'Digitaliza Aprovado Enviado', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digital_lamonica_titulo', label: 'Digital Lamonica Título', tipo: 'text', categoria: 'Digital Lamonica' },
  { chave: 'digital_lamonica_periodicidade', label: 'Digital Lamonica Periodicidade', tipo: 'text', categoria: 'Digital Lamonica' },
  { chave: 'digital_lamonica_programacao', label: 'Digital Lamonica Programação', tipo: 'text', categoria: 'Digital Lamonica' },
  { chave: 'digital_lamonica_envio', label: 'Digital Lamonica Envio', tipo: 'text', categoria: 'Digital Lamonica' },
  { chave: 'digital_lamonica_status', label: 'Digital Lamonica Status', tipo: 'text', categoria: 'Digital Lamonica' },
  { chave: 'bancah_categoria', label: 'Bancah Categoria', tipo: 'text', categoria: 'Bancah' },
  { chave: 'bancah_titulos_chapeu', label: 'Bancah Títulos Chapéu', tipo: 'text', categoria: 'Bancah' },
  { chave: 'bancah_pperiodicidade', label: 'Bancah Periodicidade', tipo: 'text', categoria: 'Bancah' },
  { chave: 'bancah_programcao', label: 'Bancah Programação', tipo: 'text', categoria: 'Bancah' },
  { chave: 'bancah_envio', label: 'Bancah Envio', tipo: 'text', categoria: 'Bancah' },
  { chave: 'bancah_status', label: 'Bancah Status', tipo: 'text', categoria: 'Bancah' },
  { chave: 'bennu_titulos', label: 'Bennu Títulos', tipo: 'text', categoria: 'Bennu' },
  { chave: 'bennu_periodicidade', label: 'Bennu Periodicidade', tipo: 'text', categoria: 'Bennu' },
  { chave: 'bennu_programacao', label: 'Bennu Programação', tipo: 'text', categoria: 'Bennu' },
  { chave: 'bennu_envio', label: 'Bennu Envio', tipo: 'text', categoria: 'Bennu' },
  { chave: 'bennu_status', label: 'Bennu Status', tipo: 'text', categoria: 'Bennu' },
  { chave: 'bookplay_categoria', label: 'Bookplay Categoria', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'bookplay_titulo', label: 'Bookplay Título', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'bookplay_cid', label: 'Bookplay CID', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'bookplay_periodicidade', label: 'Bookplay Periodicidade', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'bookplay_programacao', label: 'Bookplay Programação', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'bookplay_envio', label: 'Bookplay Envio', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'bookplay_status', label: 'Bookplay Status', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'amazom_kindle_titulo', label: 'Amazon Kindle Título', tipo: 'text', categoria: 'Amazon Kindle' },
  { chave: 'amazom_kindle_periodicidade', label: 'Amazon Kindle Periodicidade', tipo: 'text', categoria: 'Amazon Kindle' },
  { chave: 'amazom_kindle_programacao', label: 'Amazon Kindle Programação', tipo: 'text', categoria: 'Amazon Kindle' },
  { chave: 'amazom_kindle_envio', label: 'Amazon Kindle Envio', tipo: 'text', categoria: 'Amazon Kindle' },
  { chave: 'amazom_kindle_asin', label: 'Amazon Kindle ASIN', tipo: 'text', categoria: 'Amazon Kindle' },
  { chave: 'amazom_kindle_status', label: 'Amazon Kindle Status', tipo: 'text', categoria: 'Amazon Kindle' },
  { chave: 'goread_titulo', label: 'GoRead Título', tipo: 'text', categoria: 'GoRead' },
  { chave: 'goread_categoria', label: 'GoRead Categoria', tipo: 'text', categoria: 'GoRead' },
  { chave: 'goread_programacao', label: 'GoRead Programação', tipo: 'text', categoria: 'GoRead' },
  { chave: 'goread_periodicidade', label: 'GoRead Periodicidade', tipo: 'text', categoria: 'GoRead' },
  { chave: 'goread_envio', label: 'GoRead Envio', tipo: 'text', categoria: 'GoRead' },
  { chave: 'goread_status', label: 'GoRead Status', tipo: 'text', categoria: 'GoRead' },
  { chave: 'bebanca_titulo', label: 'BeBanca Título', tipo: 'text', categoria: 'BeBanca' },
  { chave: 'bebanca_periodicidade', label: 'BeBanca Periodicidade', tipo: 'text', categoria: 'BeBanca' },
  { chave: 'bebanca_programacao', label: 'BeBanca Programação', tipo: 'text', categoria: 'BeBanca' },
  { chave: 'bebanca_envio', label: 'BeBanca Envio', tipo: 'text', categoria: 'BeBanca' },
  { chave: 'bebanca_status', label: 'BeBanca Status', tipo: 'text', categoria: 'BeBanca' },
  { chave: 'oi_fibra_upstream_titulo', label: 'Oi Fibra Upstream Título', tipo: 'text', categoria: 'Oi Fibra' },
  { chave: 'oi_fibra_upstream_programacao', label: 'Oi Fibra Upstream Programação', tipo: 'text', categoria: 'Oi Fibra' },
  { chave: 'oi_fibra_upstream_periodicidade', label: 'Oi Fibra Upstream Periodicidade', tipo: 'text', categoria: 'Oi Fibra' },
  { chave: 'oi_fibra_upstream_envio', label: 'Oi Fibra Upstream Envio', tipo: 'text', categoria: 'Oi Fibra' },
  { chave: 'oi_fibra_upstream_status', label: 'Oi Fibra Upstream Status', tipo: 'text', categoria: 'Oi Fibra' },
  { chave: 'pressreader_titulo', label: 'PressReader Título', tipo: 'text', categoria: 'PressReader' },
  { chave: 'pressreader_cid', label: 'PressReader CID', tipo: 'text', categoria: 'PressReader' },
  { chave: 'pressreader_frequencia', label: 'PressReader Frequência', tipo: 'text', categoria: 'PressReader' },
  { chave: 'pressreader_programacao', label: 'PressReader Programação', tipo: 'text', categoria: 'PressReader' },
  { chave: 'pressreader_enviado', label: 'PressReader Enviado', tipo: 'text', categoria: 'PressReader' },
  { chave: 'pressreader_status', label: 'PressReader Status', tipo: 'text', categoria: 'PressReader' },
  { chave: 'edicase_digital_status', label: 'Edicase Digital Status', tipo: 'text', categoria: 'Edicase' },
  { chave: 'ubook_banca_envio', label: 'Ubook Banca Envio', tipo: 'text', categoria: 'Ubook' },
  { chave: 'ubook_banca_status', label: 'Ubook Banca Status', tipo: 'text', categoria: 'Ubook' },
  { chave: 'ubook_audio_enviado_analise', label: 'Ubook Áudio Enviado Análise', tipo: 'text', categoria: 'Ubook' },
  { chave: 'revistarias_categoria', label: 'Revistarias Categoria', tipo: 'text', categoria: 'Revistarias' },
  { chave: 'revistarias_titulo', label: 'Revistarias Título', tipo: 'text', categoria: 'Revistarias' },
  { chave: 'revistarias_periodicidade', label: 'Revistarias Periodicidade', tipo: 'text', categoria: 'Revistarias' },
  { chave: 'revistarias_programacao', label: 'Revistarias Programação', tipo: 'text', categoria: 'Revistarias' },
  { chave: 'revistarias_data_envio_ftp', label: 'Revistarias Data Envio FTP', tipo: 'text', categoria: 'Revistarias' },
  { chave: 'revistarias_status', label: 'Revistarias Status', tipo: 'text', categoria: 'Revistarias' },
  { chave: 'magzter_titulo', label: 'Magzter Título', tipo: 'text', categoria: 'Magzter' },
  { chave: 'magzter_programacao', label: 'Magzter Programação', tipo: 'text', categoria: 'Magzter' },
  { chave: 'magzter_periodicidade', label: 'Magzter Periodicidade', tipo: 'text', categoria: 'Magzter' },
  { chave: 'magzter_envio', label: 'Magzter Envio', tipo: 'text', categoria: 'Magzter' },
  { chave: 'begamer_titulo', label: 'BeGamer Título', tipo: 'text', categoria: 'BeGamer' },
  { chave: 'begamer_periodicidade', label: 'BeGamer Periodicidade', tipo: 'text', categoria: 'BeGamer' },
  { chave: 'begamer_programacao', label: 'BeGamer Programação', tipo: 'text', categoria: 'BeGamer' },
  { chave: 'begamer_envio', label: 'BeGamer Envio', tipo: 'text', categoria: 'BeGamer' },
  { chave: 'begamer_status', label: 'BeGamer Status', tipo: 'text', categoria: 'BeGamer' },
  { chave: 'skeelo_separado', label: 'Skeelo Separado', tipo: 'text', categoria: 'Skeelo' },
  { chave: 'skeelo_aprovacao', label: 'Skeelo Aprovação', tipo: 'text', categoria: 'Skeelo' },
  { chave: 'skeelo_enviado', label: 'Skeelo Enviado', tipo: 'text', categoria: 'Skeelo' },
  { chave: 'social_comics_titulo', label: 'Social Comics Título', tipo: 'text', categoria: 'Social Comics' },
  { chave: 'social_comics_programacao', label: 'Social Comics Programação', tipo: 'text', categoria: 'Social Comics' },
  { chave: 'social_comics_data_envio', label: 'Social Comics Data Envio', tipo: 'text', categoria: 'Social Comics' },
  { chave: 'social_comics_status', label: 'Social Comics Status', tipo: 'text', categoria: 'Social Comics' },
  { chave: 'zed_data_inclu_ftp', label: 'Zed Data Inclu FTP', tipo: 'text', categoria: 'Zed' },
  { chave: 'zed_segmento_app', label: 'Zed Segmento App', tipo: 'text', categoria: 'Zed' },
  { chave: 'zed_status', label: 'Zed Status', tipo: 'text', categoria: 'Zed' }  
];

export const CATEGORIAS = [
  'Básico',
  'Elo7',
  'Estante Virtual',
  'Try Digital',
  'Mercado Livre',
  'Grande Busca',
  'Olist',
  'Magazine Luiza',
  'Marcaloop',
  'Shoope',
  'Amazom',
  'Google Negócios',
  'Via Varejo',
  'Digitaliza',
  'Digital Lamonica',
  'Bancah',
  'Bennu',
  'Bookplay',
  'Amazon Kindle',
  'GoRead',
  'BeBanca',
  'Oi Fibra',
  'PressReader',
  'Edicase',
  'Ubook',
  'Revistarias',
  'Magzter',
  'BeGamer',
  'Skeelo',
  'Social Comics',
  'Zed'
];