export const CONFIG_COLUNAS = [


  {chave: 'edicao', label: 'Edição', tipo: 'text', categoria: 'Básico'},
  { chave: 'data_pdf', label: 'Data PDF', tipo: 'date', categoria: 'Básico' },
  { chave: 'prazo_entrega', label: 'Prazo de Entrega', tipo: 'text', categoria: 'Básico' },
  { chave: 'descricao', label: 'Descrição', tipo: 'textarea', categoria: 'Básico' },
  { chave: 'chamada_principal', label: 'Chamada Principal', tipo: 'textarea', categoria: 'Básico' },
  { chave: 'descricao_edicao', label: 'Descrição Edição', tipo: 'textarea', categoria: 'Básico' },
  { chave: 'palavra_chave', label: 'Palavra Chave', tipo: 'text', categoria: 'Básico' },
  { chave: 'autor', label: 'Autor', tipo: 'text', categoria: 'Básico' },
  { chave: 'numero_pagina', label: 'Número de Páginas', tipo: 'number', categoria: 'Básico' },
  { chave: 'codigo_barra', label: 'Código de Barra', tipo: 'text', categoria: 'Básico' },
  { chave: 'ean', label: 'EAN', tipo: 'text', categoria: 'Básico' },
  { chave: 'isbn', label: 'ISBN', tipo: 'text', categoria: 'Básico' },
  { chave: 'bisac', label: 'BISAC', tipo: 'text', categoria: 'Básico' },
  { chave: 'descricao_bisac', label: 'Descrição BISAC', tipo: 'textarea', categoria: 'Básico' },
  { chave: 'categoria', label: 'Categoria', tipo: 'textarea', categoria: 'Básico' },
 { chave: 'sub_categoria', label: 'Sub Categoria', tipo: 'textarea', categoria: 'Básico' },
 { chave: 'editora', label: 'Editora', tipo: 'text', categoria: 'Básico' },
 { chave: 'periodicidade', label: 'Periodicidade', tipo: 'text', categoria: 'Básico' },
 { chave: 'observacao', label: 'Observações', tipo: 'textarea', categoria: 'Básico' },
  
  { chave: 'google_negocios_digital', label: ' Digital', tipo: 'text', categoria: 'Google Negócios' },
  { chave: 'google_negocios_impresso', label: ' Impresso', tipo: 'text', categoria: 'Google Negócios' },
  { chave: 'via_varejo_impresso', label: ' Impresso', tipo: 'text', categoria: 'Via Varejo' },
  { chave: 'digitaliza_pdf', label: ' PDF', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_epub', label: ' EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_metadados_digit', label: 'Metadados Digit', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_solic_exclusao', label: 'Solic Exclusão', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_24symbolo_epub', label: '24Symbolo EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_amazom_epub', label: 'Amazom EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_apple_epub', label: 'Apple EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_arvoresdelivros_epub', label: 'Árvores de Livros EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_bem_te_li_epub', label: 'Bem-te-li EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_google_pdf', label: 'Google PDF', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_kobo_epub', label: 'Kobo EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_livraria_cultura_epub', label: 'Livraria Cultura EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_nook_barners_noble', label: 'Nook Barnes Noble', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_saraiva', label: 'Saraiva', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_toca_livros', label: 'Toca Livros', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_ubook', label: 'Ubook', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_ubool_store_epub', label: 'Ubool Store EPUB', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_', label: 'Digitaliza', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_epub_enviado', label: 'EPUB Enviado', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digitaliza_aprovado_enviado', label: 'Aprovado Enviado', tipo: 'text', categoria: 'Digitaliza' },
  { chave: 'digital_lamonica_titulo', label: 'Título', tipo: 'text', categoria: 'Dig Lamonica' },
  { chave: 'digital_lamonica_periodicidade', label: 'Periodicidade', tipo: 'text', categoria: 'Dig Lamonica' },
  { chave: 'digital_lamonica_programacao', label: 'Programação', tipo: 'text', categoria: 'Dig Lamonica' },
  { chave: 'digital_lamonica_envio', label: 'Envio', tipo: 'text', categoria: 'Dig Lamonica' },
  { chave: 'digital_lamonica_status', label: 'Status', tipo: 'text', categoria: 'Dig Lamonica' },
  { chave: 'bancah_categoria', label: ' Categoria', tipo: 'text', categoria: 'Bancah' },
  { chave: 'bancah_titulos_chapeu', label: ' Títulos Chapéu', tipo: 'text', categoria: 'Bancah' },
  { chave: 'bancah_pperiodicidade', label: ' Periodicidade', tipo: 'text', categoria: 'Bancah' },
  { chave: 'bancah_programcao', label: ' Programação', tipo: 'text', categoria: 'Bancah' },
  { chave: 'bancah_envio', label: ' Envio', tipo: 'text', categoria: 'Bancah' },
  { chave: 'bancah_status', label: ' Status', tipo: 'text', categoria: 'Bancah' },
  { chave: 'bennu_titulos', label: ' Títulos', tipo: 'text', categoria: 'Bennu' },
  { chave: 'bennu_periodicidade', label: ' Periodicidade', tipo: 'text', categoria: 'Bennu' },
  { chave: 'bennu_programacao', label: ' Programação', tipo: 'text', categoria: 'Bennu' },
  { chave: 'bennu_envio', label: ' Envio', tipo: 'text', categoria: 'Bennu' },
  { chave: 'bennu_status', label: ' Status', tipo: 'text', categoria: 'Bennu' },
  { chave: 'bookplay_categoria', label: ' Categoria', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'bookplay_titulo', label: ' Título', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'bookplay_cid', label: ' CID', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'bookplay_periodicidade', label: ' Periodicidade', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'bookplay_programacao', label: ' Programação', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'bookplay_envio', label: ' Envio', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'bookplay_status', label: ' Status', tipo: 'text', categoria: 'Bookplay' },
  { chave: 'amazom_kindle_titulo', label: 'Título', tipo: 'text', categoria: 'Amazon Kindle' },
  { chave: 'amazom_kindle_periodicidade', label: 'Periodicidade', tipo: 'text', categoria: 'Amazon Kindle' },
  { chave: 'amazom_kindle_programacao', label: 'Programação', tipo: 'text', categoria: 'Amazon Kindle' },
  { chave: 'amazom_kindle_envio', label: 'Envio', tipo: 'text', categoria: 'Amazon Kindle' },
  { chave: 'amazom_kindle_asin', label: ' ASIN', tipo: 'text', categoria: 'Amazon Kindle' },
  { chave: 'amazom_kindle_status', label: 'Status', tipo: 'text', categoria: 'Amazon Kindle' },
  { chave: 'goread_titulo', label: ' Título', tipo: 'text', categoria: 'GoRead' },
  { chave: 'goread_categoria', label: ' Categoria', tipo: 'text', categoria: 'GoRead' },
  { chave: 'goread_programacao', label: ' Programação', tipo: 'text', categoria: 'GoRead' },
  { chave: 'goread_periodicidade', label: ' Periodicidade', tipo: 'text', categoria: 'GoRead' },
  { chave: 'goread_envio', label: ' Envio', tipo: 'text', categoria: 'GoRead' },
  { chave: 'goread_status', label: ' Status', tipo: 'text', categoria: 'GoRead' },
  { chave: 'bebanca_titulo', label: ' Título', tipo: 'text', categoria: 'BeBanca' },
  { chave: 'bebanca_periodicidade', label: ' Periodicidade', tipo: 'text', categoria: 'BeBanca' },
  { chave: 'bebanca_programacao', label: ' Programação', tipo: 'text', categoria: 'BeBanca' },
  { chave: 'bebanca_envio', label: ' Envio', tipo: 'text', categoria: 'BeBanca' },
  { chave: 'bebanca_status', label: ' Status', tipo: 'text', categoria: 'BeBanca' },
  { chave: 'oi_fibra_upstream_titulo', label: 'Upstream Título', tipo: 'text', categoria: 'Oi Fibra' },
  { chave: 'oi_fibra_upstream_programacao', label: 'Upstream Programação', tipo: 'text', categoria: 'Oi Fibra' },
  { chave: 'oi_fibra_upstream_periodicidade', label: ' Upstream Periodicidade', tipo: 'text', categoria: 'Oi Fibra' },
  { chave: 'oi_fibra_upstream_envio', label: 'Upstream Envio', tipo: 'text', categoria: 'Oi Fibra' },
  { chave: 'oi_fibra_upstream_status', label: 'Upstream Status', tipo: 'text', categoria: 'Oi Fibra' },
  { chave: 'pressreader_titulo', label: 'Título', tipo: 'text', categoria: 'PressReader' },
  { chave: 'pressreader_cid', label: 'CID', tipo: 'text', categoria: 'PressReader' },
  { chave: 'pressreader_frequencia', label: 'Frequência', tipo: 'text', categoria: 'PressReader' },
  { chave: 'pressreader_programacao', label: ' rogramação', tipo: 'text', categoria: 'PressReader' },
  { chave: 'pressreader_enviado', label: 'Enviado', tipo: 'text', categoria: 'PressReader' },
  { chave: 'pressreader_status', label: 'Status', tipo: 'text', categoria: 'PressReader' },
  { chave: 'edicase_digital_status', label: 'Status', tipo: 'text', categoria: 'Edicase' },
  { chave: 'ubook_banca_envio', label: 'Envio', tipo: 'text', categoria: 'Ubook' },
  { chave: 'ubook_banca_status', label: 'Utatus', tipo: 'text', categoria: 'Ubook' },
  { chave: 'ubook_audio_enviado_analise', label: ' nviado Análise', tipo: 'text', categoria: 'Ubook' },
  { chave: 'revistarias_categoria', label: 'Categoria', tipo: 'text', categoria: 'Revistarias' },
  { chave: 'revistarias_titulo', label: 'Título', tipo: 'text', categoria: 'Revistarias' },
  { chave: 'revistarias_periodicidade', label: 'Periodicidade', tipo: 'text', categoria: 'Revistarias' },
  { chave: 'revistarias_programacao', label: 'Programação', tipo: 'text', categoria: 'Revistarias' },
  { chave: 'revistarias_data_envio_ftp', label: 'Data Envio FTP', tipo: 'text', categoria: 'Revistarias' },
  { chave: 'revistarias_status', label: 'Status', tipo: 'text', categoria: 'Revistarias' },
  { chave: 'magzter_titulo', label: 'Título', tipo: 'text', categoria: 'Magzter' },
  { chave: 'magzter_programacao', label: 'Programação', tipo: 'text', categoria: 'Magzter' },
  { chave: 'magzter_periodicidade', label: 'Periodicidade', tipo: 'text', categoria: 'Magzter' },
  { chave: 'magzter_envio', label: 'Envio', tipo: 'text', categoria: 'Magzter' },
  { chave: 'begamer_titulo', label: 'Título', tipo: 'text', categoria: 'BeGamer' },
  { chave: 'begamer_periodicidade', label: 'Periodicidade', tipo: 'text', categoria: 'BeGamer' },
  { chave: 'begamer_programacao', label: 'Programação', tipo: 'text', categoria: 'BeGamer' },
  { chave: 'begamer_envio', label: 'Envio', tipo: 'text', categoria: 'BeGamer' },
  { chave: 'begamer_status', label: 'Status', tipo: 'text', categoria: 'BeGamer' },
  { chave: 'skeelo_separado', label: 'Separado', tipo: 'text', categoria: 'Skeelo' },
  { chave: 'skeelo_aprovacao', label: 'Aprovação', tipo: 'text', categoria: 'Skeelo' },
  { chave: 'skeelo_enviado', label: 'Enviado', tipo: 'text', categoria: 'Skeelo' },
  { chave: 'social_comics_titulo', label: 'Título', tipo: 'text', categoria: 'Social Comics' },
  { chave: 'social_comics_programacao', label: 'Programação', tipo: 'text', categoria: 'Social Comics' },
  { chave: 'social_comics_data_envio', label: 'Data Envio', tipo: 'text', categoria: 'Social Comics' },
  { chave: 'social_comics_status', label: 'Status', tipo: 'text', categoria: 'Social Comics' },
  { chave: 'zed_data_inclu_ftp', label: 'Data Inclu FTP', tipo: 'text', categoria: 'Zed' },
  { chave: 'zed_segmento_app', label: 'Segmento App', tipo: 'text', categoria: 'Zed' },
  { chave: 'zed_status', label: 'Status', tipo: 'text', categoria: 'Zed' },
  { chave: 'elo7_impresso', label: 'Impresso', tipo: 'text', categoria: 'Elo7' }, 
  { chave: 'elo7_digital', label: 'Digital', tipo: 'text', categoria: 'Elo7' },
   { chave: 'estante_virtual_cadastro', label: 'Cadastro', tipo: 'text', categoria: 'Estante Virtual' },
   { chave: 'loja_try_digital_titulo', label: 'Digital Título', tipo: 'text', categoria: 'Try Digital' },
   { chave: 'loja_try_digital_programacao', label: ' Programação', tipo: 'text', categoria: 'Try Digital' },
   { chave: 'loja_try_digital_data', label: 'Digital', tipo: 'date', categoria: 'Try Digital' },
   { chave: 'loja_try_impresso_data', label: 'Impresso ', tipo: 'date', categoria: 'Try Digital' },
   { chave: 'mercado_livre_impresso', label: 'Impresso', tipo: 'text', categoria: 'Mercado Livre' },
   { chave: 'mercado_livre_digital', label: 'Digital', tipo: 'text', categoria: 'Mercado Livre' },
   { chave: 'grande_busca_impresso', label: 'Impresso', tipo: 'text', categoria: 'Grande Busca' },
   { chave: 'grande_busca_digital', label: 'Busca ', tipo: 'text', categoria: 'Grande Busca' },
   { chave: 'olist_impresso', label: 'Impresso', tipo: 'text', categoria: 'Olist' },
   { chave: 'magazine_luiza_impresso', label: 'Luiza Impresso', tipo: 'text', categoria: 'Magazine Luiza' },
   { chave: 'marcaloop_impresso', label: 'Impresso', tipo: 'text', categoria: 'Marcaloop' },
   { chave: 'marcaloop_digital', label: 'Digital', tipo: 'text', categoria: 'Marcaloop' },
   { chave: 'shopee_impresso', label: 'Impresso', tipo: 'text', categoria: 'Shoope' },
   { chave: 'shopee_digital', label: 'Digital', tipo: 'text', categoria: 'Shoope' },
   { chave: 'amazom_impresso', label: 'Impresso', tipo: 'text', categoria: 'Amazon' },
];


export const CORES_CATEGORIAS = {
  // Institucional / Geral
  'Básico': '#64748b', // Slate

  // Ecossistema Amazon (Laranjas)
  'Amazon Kindle': '#ff9900',
  'Amazon': '#ff9900',

  // Plataformas de Leitura/Bancas (Azuis e Roxos)
  'Bancah': '#6366f1',
  'BeBanca': '#8b5cf6',
  'GoRead': '#3b82f6',
  'Magzter': '#2563eb',
  'PressReader': '#1d4ed8',
  'Revistarias': '#4338ca',

  // Digitaliza e Serviços (Verdes)
  'Digitaliza': '#10b981',
  'Dig Lamonica': '#059669',
  'Skeelo': '#047857',
  'Ubook': '#064e3b',

  // Marketplaces e Vendas (Amarelos/Laranjas Fortes)
  'Mercado Livre': '#ffe600',
  'Magazine Luiza': '#0086ff',
  'Shoope': '#ee4d2d',
  'Olist': '#212121',
  'Elo7': '#fead01',
  'Estante Virtual': '#004a80',
  'Via Varejo': '#e61e28',

  // Outros Serviços (Diversos)
  'Google Negócios': '#ea4335',
  'Oi Fibra': '#ff007f',
  'Social Comics': '#ed1c24',
  'Try Digital': '#1abc9c',
  'Zed': '#34495e',
  'Bennu': '#d35400',
  'Bookplay': '#2980b9',
  'BeGamer': '#7f8c8d',
  'Grande Busca': '#27ae60',
  'Marcaloop': '#8e44ad',
  'Edicase': '#c0392b'
};

export const COR_PADRAO = '#cbd5e1';